# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14f047ebafb127006aead6b8a462bc86de826400f477190c1e535db90b22a6c655e3b231ffed1a38c259594c4db302ebb3c4770a87404163bfe0947b720a1bf0

test:
  secret_key_base: 7a3e69b04d68931c6723ab3b9f00fbdf680a0498e7c9a287c8e44b8fd447b793f46d625bae78e7899192f77d800a7de2d4378fbc05e510ec5a0ebac359ab8e31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
